Tuple

In [1]:
# Creating a tuple
my_tuple = ('apple', 'banana', 'cherry', 10, 20)

# Accessing elements in a tuple
print("Tuple:", my_tuple)
print("First element:", my_tuple[0])
print("Second element:", my_tuple[1])
print("Slicing the tuple:", my_tuple[1:4])

# Tuple unpacking
fruit1, fruit2, *numbers = my_tuple
print("Unpacked fruits:", fruit1, fruit2)
print("Unpacked numbers:", numbers)

Tuple: ('apple', 'banana', 'cherry', 10, 20)
First element: apple
Second element: banana
Slicing the tuple: ('banana', 'cherry', 10)
Unpacked fruits: apple banana
Unpacked numbers: ['cherry', 10, 20]

Dictionary

In [2]:
# Creating a dictionary
my_dict = {
    'name': 'John',
    'age': 25,
    'city': 'New York',
    'grades': {'math': 90, 'english': 85, 'history': 88}
}

# Accessing elements in a dictionary
print("Dictionary:", my_dict)
print("Name:", my_dict['name'])
print("Age:", my_dict['age'])
print("City:", my_dict['city'])
print("Math grade:", my_dict['grades']['math'])

# Modifying dictionary
my_dict['age'] = 26
my_dict['grades']['math'] = 95

# Adding a new key-value pair
my_dict['gender'] = 'Male'

# Deleting a key-value pair
del my_dict['grades']['history']

print("Modified Dictionary:", my_dict)

Dictionary: {'name': 'John', 'age': 25, 'city': 'New York', 'grades': {'math': 90, 'english': 85, 'history': 88}}
Name: John
Age: 25
City: New York
Math grade: 90
Modified Dictionary: {'name': 'John', 'age': 26, 'city': 'New York', 'grades': {'math': 95, 'english': 85}, 'gender': 'Male'}